server:
  port: 7050
management:
  port: 7056
  context-path: /
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    metadata-map:
      cluster: prontera
      management:
        port: ${management.port}
        context-path: ${management.context-path}
      health:
        path: ${management.context-path}/health
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 10
spring:
  application:
    name: lm.cloud.boot.admin.server
  cloud:
    loadbalancer:
      retry:
        enabled: true
  boot:
    admin:
      turbine:
        url: http://localhost:7040/turbine.stream
        clusters: prontera